# Configura��es da aplica��o Spring Boot
spring:
  application:
    name: eurekaserver  # Nome da aplica��o (usado para identifica��o no Eureka)
  security:
    basic:
      enabled: true
    user:
      name: cursoms-eureka-user
      password: hadouken


# Porta em que o servidor ir� rodar
server:
  port: 8761  # Porta padr�o do Eureka Server

# Configura��es espec�ficas do Eureka
eureka:
  client:
    register-with-eureka: false  # Este servidor n�o deve se registrar como cliente (pois ele � o servidor)
    fetch-registry: false        # Este servidor n�o precisa buscar registros (ele � quem os fornece)
